//Sadman Sakib Ahmed

void write_book();
void write_dvd();
void writeTape();
void write_student();
void display_spb(char n[]);
void display_spd(char n[]);
void display_sps(char n[]);
void printSpecificTape(char n[]);
void modify_book();
void modify_dvd();
void modify_student();
void modifyTape();
void delete_student();
void delete_book();
void delete_dvd();
void deleteTape();
void display_alls();
void display_allb();
void display_alld();
void displayAllTapes();
void book_issue();
void dvd_issue();
void book_deposit();
void dvd_deposit();
void issueTape();
void depositeTape();
void intro();
void admin_menu();
